betagouv/espace-membre-next

- src/components/Header.tsx
Comm**a**unauté -> Communauté.
> fix: Correction d'une faute d'orthographe dans le header

- src/components/AccountPage/BlocAccederAuWebmail.tsx
- src/components/AccountPage/EmailContainer.tsx
For Exchange users : 
- hide `BlocEmailResponder` and `BlocRedirection`
- fix webmail URL
fix #2140
> fix(account): fix exchange options

- src/app/(public)/signin/SiginClientPage.tsx
- auto-submit login form with token from client-side hash 
- redirect already logged-in users
- show error message if any
> fix(login): click-less magic link

- src/components/LoginPage/Login.tsx
> fix(login): show error on unknown email fix #32

- src/components/BaseInfoUpdatePage/BaseInfoUpdate.tsx
for https://github.com/betagouv/beta.gouv.fr/issues/18233
> chore: wording

- src/server/controllers/onboardingController/getConfirmation.ts
- src/server/controllers/onboardingController/getOnboardingForm.ts
- src/server/controllers/onboardingController/postOnboardingForm.ts
- src/server/controllers/usersController/createRedirectionForUser.ts
> Redirs errors

- src/app/(private)/(dashboard)/account/base-info/page.tsx
fix [this error](https://sentry.incubateur.net/organizations/betagouv/issues/88163/?alert_rule_id=103&alert_timestamp=1708944898469&alert_type=email&environment=production&project=143&referrer=alert_email)
> fix(account/base-info): prevent exception when startups=null

- src/app/(private)/(dashboard)/account/base-info/page.tsx
fix https://sentry.incubateur.net/organizations/betagouv/issues/88243/?alert_rule_id=103&alert_timestamp=1709022040096&alert_type=email&project=143&referrer=digest_email
> fix(membres/base-info): prevent null bio exception

- .talismanrc
- src/app/(public)/login/page.tsx
- src/components/BaseInfoUpdatePage/BaseInfoUpdate.tsx
redirect from login to account when already logged-in
> chore: wording and redirection

- src/app/(public)/onboardingSuccess/[prNumber]/page.tsx
- src/server/views/templates/markdown/githubAuthor.ejs
Lors de la création de fiche, ajout de la startup dans la mission du membre
> fix(create-fiche): set startup in missions

- src/models/startup.ts
fix https://sentry.incubateur.net/organizations/betagouv/issues/91053/?project=143&referrer=webhooks_plugin
> fix(edit-produit): typo

- .talismanrc
- src/app/error.tsx
- src/components/BaseInfoUpdatePage/BaseInfoUpdate.tsx
- src/components/BaseInfoUpdatePage/CompetencesEditor.tsx
- src/components/BaseInfoUpdatePage/MissionsEditor.tsx
- src/models/competences.ts
- src/models/member.ts
- src/models/mission.ts
Add competences in member/base-info
existing competences extracted from website data
> feat: add membre.competences

- src/components/MemberPage/MemberBrevoEventList.tsx
> fix: fix community member exception

- src/components/MemberPage/MemberPage.tsx
> fix(community/member): show primary email

- .talismanrc
- package-lock.json
- package.json
- src/scripts/export-to-www.ts
- src/scripts/github-schemas.ts
- src/scripts/import-from-www.ts
- src/scripts/utils.ts
- add `npm run import-from-www` : use betagouv master.zip and update local DB
- add `npm run export-to-www` : use local DB and update files in some folder
Dans un 1er temps l'export des modifs pourrait être automatisé pour produire une PR ?
Exemple de PR suite à export : https://github.com/betagouv/beta.gouv.fr/pull/20131
> feat: add import/export scripts

- README.md
- e2e/community.spec.ts
- playwright.config.ts
- src/app/(private)/(dashboard)/community/create/CommunityCreateMemberPage.tsx
- src/components/BaseInfoUpdatePage/BaseInfoUpdate.tsx
- src/components/BaseInfoUpdatePage/CompetencesEditor.tsx
- src/components/BaseInfoUpdatePage/MissionsEditor.tsx
- src/components/MemberPage/MemberPage.tsx
- src/models/mapper/index.ts
- src/models/mission.ts
- src/server/schedulers/cron.ts
- src/server/schedulers/mattermostScheduler/createUsersByEmail.ts
- src/server/schedulers/mattermostScheduler/index.ts
- src/server/schedulers/mattermostScheduler/inviteUserToTeamByEmail.ts
- correction test e2e
- cosmetic fix fiche membre
- fix #255 
- fix #260 
- fix #252 
- fix #257
> small fixes

- package.json
- src/scripts/export-to-www.sh
- src/scripts/github-schemas.ts
- src/scripts/update-local-files.ts
> fix: export-to-www

- src/app/(private)/(dashboard)/dashboard/DashboardPage.tsx
> fix: Update DashboardPage.tsx

- src/scripts/utils.ts
permet d'enlever les quotes autour de certaines dates à l'export :/
> fix(export): prevent quoted dates

- src/models/sponsor.ts
https://sentry.incubateur.net/organizations/betagouv/issues/110038/events/f35ca26dc5724d64a174e0f18a6b349c/
> fix(model): restore spm value

- cron.json
> feat: automate export with cron.json

- src/components/CommunityPage/CommunitySearchMember.tsx
fix https://sentry.incubateur.net/organizations/betagouv/issues/110588/?project=143&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0
> fix(community): enable button when selected only

- .talismanrc
- src/app/(private)/(dashboard)/PrivateLayout.tsx
- src/app/(private)/(dashboard)/metabase/page.tsx
- src/components/Header.tsx
- src/utils/routes/list.ts
- src/utils/routes/localizedRoutes.ts
- src/utils/routes/registry.ts
- src/utils/routes/routeTitles.ts
Ajout d'une vue metabase vers le dashboard metabase communauté pulic : https://metabase.incubateur.net/dashboard/16-communaute-public
je ne sais pas comment gérer le breadcrumb ou pourquoi le menu ne s'affiche pas 🤔
> feat(community): add metabase view

- .talismanrc
- src/app/(public)/login/page.tsx
- src/components/LoginPage/Login.tsx
- src/server/schedulers/emailScheduler.ts
On passe l'email en query params dans le premier email. Si le query params avec l'email secondaire est dans l'url. On affiche une page de connexion light avec juste le nécessaire pour ne pas perdre l'utilisateur.
> chore: personalized screen for first connexion

- package-lock.json
- package.json
- src/app/(private)/(dashboard)/dashboard/DashboardPage.tsx
- src/app/(private)/(dashboard)/dashboard/page.tsx
- src/components/SurveyBox.tsx
The cookie expiration is set to 7 days, feel free to tune as necessary
> feat(home): add survey box fix #338

- src/lib/kysely/queries/users.ts
prevent displaying empty startups
> fix(members): hide startups when empty

- .talismanrc
- cron.json
- src/lib/github.ts
- src/server/controllers/adminController/adminController.ts
- src/server/routes/admin.ts
> fix: use -cron to udpate github

- src/app/(private)/(dashboard)/community/create/CommunityCreateMemberPage.tsx
changement de wording sur le champ "email" de la création d'une fiche.
Ce n'est pas assez clair de ce qu'on m'a remonté
> chore(create-member): adjust email label and hint

- src/app/(private)/(dashboard)/account/base-info/page.tsx
- src/app/(private)/(dashboard)/community/[id]/admin-update/page.tsx
- src/app/(private)/(dashboard)/community/[id]/page.tsx
- src/app/api/member/updateMember.ts
- src/components/BaseInfoUpdatePage/BaseInfoUpdate.tsx
- src/components/LastChange.tsx
- src/components/MemberPage/MemberPage.tsx
- src/lib/events.ts
- src/models/mapper/index.ts
- src/models/memberChange.ts
Affiche les infos sur la dernière modif dans la fiche membre
> feat: add member last edit info

- src/app/api/member/[username]/route.ts
- src/app/layout.tsx
- src/components/BaseInfoUpdatePage/BaseInfoUpdate.tsx
- src/components/Header.tsx
- src/components/IncubatorListPage/IncubatorList.tsx
- src/components/SelectAccessibilityStatus.tsx
- src/components/Skiplinks.tsx
- src/components/StartupForm/SponsorBlock.tsx
- src/components/StartupForm/StartupForm.tsx
- src/components/StartupListPage/StartupList.tsx
- src/components/organization/OrganizationListPage/OrganizationList.tsx
- src/components/team/TeamListPage/TeamList.tsx
- src/utils/routes/routeTitles.ts
- ✨ Affiche des boutons plutôt que des liens "Créer une nouvelle fiche"
- 🐛 Corrige quelques problèmes d'accessibilité (utilisation de balise `<br>` pour de la mise en page)
- 🧹 Simplifie certains wording de formulaire
- 🆕 Ajoute des liens d'évitement pour les gens qui naviguent au clavier
- 🤓 Corrige la mention d'accessibilité (non conforme, et pas partiellement conforme)
> Fix UI - UX

- .talismanrc
- e2e/community.spec.ts
- src/app/(private)/(dashboard)/incubators/page.tsx
- src/app/(private)/(dashboard)/organizations/page.tsx
- src/app/(private)/(dashboard)/startups/page.tsx
- src/components/AutoComplete.tsx
- src/components/BaseInfoUpdatePage/CompetencesEditor.tsx
- src/components/CommunityPage/CommunityFilterMembers.tsx
- src/components/DomaineSelect.tsx
- src/components/IncubatorForm/IncubatorForm.tsx
- src/components/MemberSelect.tsx
- src/components/MemberStatusSelect.tsx
- src/components/SEPhaseSelect.tsx
- src/components/SESelect.tsx
- src/components/SESponsorSelect.tsx
- src/components/StartupForm/SponsorBlock.tsx
- src/components/StartupForm/ThematiquesEditor.tsx
- src/components/StartupForm/UsertypesEditor.tsx
- src/components/StartupListPage/StartupList.tsx
- src/components/organization/OrganizationListPage/OrganizationList.tsx
From issue https://github.com/betagouv/espace-membre-next/issues/215
`src/components/CitySelect.tsx` est plus compliqué et non migré pour le moment
> chore(ui): abstract and simplify AutoComplete component

- src/lib/matomo.ts
It is recommended to use POST request instead of get request when calling matomo api
> chore: use POST request for matomo instead of GET for safety

- src/app/(private)/(dashboard)/PrivateLayout.tsx
> chore: commenting badge feature temporarilchore: commenting badge

- src/app/(public)/accessibilite/page.tsx
- src/app/(public)/components/page.tsx
- src/app/layout.tsx
ajout de la page /accessibilite
fix #329
> fix: add declaration a11y

- .talismanrc
- package.json
- src/app/(private)/(dashboard)/community/page.tsx
- src/components/CommunityPage/Community.tsx
- src/lib/kysely/queries/incubators.ts
fix #611 https://sentry.incubateur.net/organizations/betagouv/issues/127691/
replace with a single query
> fix(community): fix SQL perf issue

- __tests__/test-user-contract-ending.ts
- src/server/schedulers/setEmailExpired.ts
fix migration error when using kysely instead of knex/github
> fix: email is set as expired when email is not a beta.gouv.fr address

- e2e/incubator.spec.ts
- src/app/(private)/(dashboard)/PrivateLayout.tsx
- src/app/(private)/(dashboard)/community/[id]/admin-update/page.tsx
- src/app/(private)/(dashboard)/community/[id]/page.tsx
- src/app/(private)/(dashboard)/community/[id]/update/page.tsx
- src/app/(private)/(dashboard)/formations/[id]/page.tsx
- src/app/(private)/(dashboard)/incubators/[id]/info-form/page.tsx
- src/app/(private)/(dashboard)/incubators/[id]/page.tsx
- src/app/(private)/(dashboard)/organizations/[id]/info-form/page.tsx
- src/app/(private)/(dashboard)/organizations/[id]/page.tsx
- src/app/(private)/(dashboard)/startups/[id]/files/page.tsx
- src/app/(private)/(dashboard)/startups/[id]/info-form/page.tsx
- src/app/(private)/(dashboard)/startups/[id]/page.tsx
- src/app/(private)/(dashboard)/teams/[id]/info-form/page.tsx
- src/app/(private)/(dashboard)/teams/[id]/page.tsx
- src/app/BreadCrumbProvider.tsx
- src/components/CommunityPage/Community.tsx
- src/components/Header.tsx
- src/components/IncubatorPage/IncubatorPage.tsx
- src/components/IncubatorUpdatePage/IncubatorUpdate.tsx
- src/components/StartupInfoUpdatePage/StartupInfoUpdate.tsx
- src/components/StartupPage/StartupPage.tsx
- src/components/organization/OrganizationPage/Organization.tsx
- src/components/organization/OrganizationUpdatePage/OrganizationUpdate.tsx
- src/components/team/TeamPage/Team.tsx
- src/components/team/TeamUpdatePage/TeamUpdate.tsx
> chore: removed sidemenu, add submenu to dropdown

- src/app/(private)/(dashboard)/dashboard/DashboardPage.tsx
Mise à jour des cartes sur la home
> fix(home): update tiles

- src/app/(private)/(dashboard)/account/page.tsx
- src/app/(private)/(dashboard)/community/[id]/page.tsx
- src/app/(public)/components/page.tsx
- src/app/api/member/actions.ts
- src/components/MemberPage/Email/EmailContainer.tsx
- src/components/MemberPage/MemberCard.tsx
- src/components/MemberPage/MemberContact.tsx
- src/components/MemberPage/MemberPage.tsx
- src/lib/kysely/queries/teams.ts
- src/server/config/admin.config.ts
- src/server/config/index.ts
En tant que membre d'une équipe transverse de l'incubateur A, je peux terminer la mission d'un membre travaillant pour une équipe qui dépend de mon incubateur (l'incubateur A).
> feat: add incubator admin authorization

- src/app/api/protected/member/[username]/route.ts
- src/components/CommunityPage/Community.tsx
- src/components/CommunityPage/utils.ts
- src/middleware.ts
- src/utils/member.ts
- add `isActive` to return payload
- add "incubateur.net" in default allowed origin list
> feat(api): protected get member return isActive

- src/components/MemberPage/MemberPage.tsx
exemple: https://espace-membre-staging-pr733.osc-fr1.scalingo.io/account#compte-email
> chore: show specific tab depending on hash value

- src/app/(public)/signin/SiginClientPage.tsx
Reverts betagouv/espace-membre-next#742
> Revert "chore: remove autoSubmit for francetravail"

- src/components/StartupPage/StartupHistory.tsx
- src/components/StartupPage/timeline.css
> fix(startup): fix events display

- .talismanrc
- src/models/member.ts
Ajout d'un statut légal manquant
> fix(membre): add legal_status.salarie_agence

- e2e/member.edit.spec.ts
- src/app/api/member/actions/index.ts
- src/models/actions/member.ts
> feat: prevent update of more than 6 months in the future for non "Agent Public" users

- src/models/incubator.ts
> feat: contact must be an email

- src/app/(private)/(dashboard)/services/page.tsx
- src/components/BadgeEmailPlan.tsx
- src/components/MemberPage/Email/EmailContainer.tsx
- src/components/MemberPage/MemberContact.tsx
- src/components/MemberPage/MemberStatus.tsx
- src/components/StartupPage/StartupStandards.tsx
Many hydration errors are due to Badge being used inside "p" tag, and Badge default is "p".
> chore: use span on all Badge components

- migrations/20250314092134_add_impact_url_to_startups.ts
- package-lock.json
- src/@types/db.d.ts
- src/components/StartupForm/StartupForm.tsx
- src/components/StartupPage/StartupStandards.tsx
- src/models/actions/startup.ts
- src/models/startup.ts
fix #854
formulaire :
onglet standards :
une fois que c'est bon sur espace-membre on fera l'ajout sur la fiche sur le site beta.gouv
> feat: add startup.impact_url

- src/server/views/templates/emails/mail30days.ejs
Pour ne pas avoir à rechercher l’adresse de l’espace membre j’ajoute le lien dans le mail.
> feat: add espace-membre link in email

- src/components/FichePicture.tsx
> fix(ImagePreview): use contain instead of cover

- public/onboarding/checklist.yml
Distinction des 2 étapes d'embarquement :
1/ atelier en visio
2/ atelier en présentiel
> Ajout distinction ateliers d'embarquement

- .gitmodules
- .talismanrc
- README.md
Le storybook de espace-membre dans un submodule à part
> docs: add storybook submodule

- src/scripts/update-local-files.ts
il manque le cas où la personne n'a plus d'équipe... (teams.length===0)
> fix(export): always update users teams

- src/components/MemberPage/Email/EmailContainer.tsx
> fix(wording): be more explicit when email creating is pending

- src/server/schedulers/userContractEndingScheduler.ts
fix #1057
Also serialize notifications calls to prevent flooding
> fix: fix wrong contract ending date message

- src/app/(private)/(dashboard)/PrivateLayout.tsx
- src/components/Header.tsx
Ajout d'une entrée dans le menu communauté pour l'observatoire
> feat: add Communauté/Observatoire menu entry
