- src/components/SponsorForm/SponsorDomainSelect.tsx
- src/components/SponsorForm/SponsorForm.tsx
- src/components/SponsorForm/SponsorTypeSelect.tsx
- src/components/StartupForm/SponsorBlock.tsx
- src/components/StartupForm/StartupForm.tsx
Cette PR entraine d'autre soucis. On ne peut plus sauvegarder le formulaire du tout car les navigateurs considères les champs du formulaire sponsor comme des champs du formulaire parent.
> Revert "fix: remove form within form to avoid form submission, add preventDef…"

- src/components/NewsletterPage/NewsletterPage.tsx
Il me semble que la condition est inversée (`newsletters.length && (<p>Il n'y a pas d'infolettres dans l'historique</p>)`) ce qui fait que le message apparaît systématiquement alors qu'il y a clairement un historique.
Je dois signaler que je n'ai pas pris le temps de tester le changement proposé en local.
> fix(newsletter): le message "Il n'y a pas d'infolettres dans l'historique" n'apparaît que s'il y a un historique

- .husky/pre-commit
- .talismanrc
- package-lock.json
- package.json
Ajout d'un precommit hook [talisman](https://github.com/thoughtworks/talisman) pour éviter un commit de secret.
Quand un nouveau secret est détecté lors du `git commit`, le CLI demandera confirmation d'ajouter ou pas la ligne suspecte à la whitelist (.talismanrc)
> feat: add talisman pre-commit hook

- package-lock.json
- package.json
- src/server/betagouv.ts
For some reason `author.role` is HTML encoded [in the API output](https://github.com/betagouv/beta.gouv.fr/blob/master/api/v2.6/authors.json#L9) which is called on some routes (ex: account home).
before:
after:
> fix(account): unescape author.role

- src/components/Formation/FormationList.tsx
Ranger les formations dans l'ordre chronologique
> fix(formations): sort by date ASC

- src/components/AccountPage/BlocConfigurerEmailPrincipal.tsx
fix #318
Add warning + confirmation dialog when changing primary email
(Suite à une cata qui a couté pas mal de support)
Before:
---
After:
(Clicks trigger a confirm dialog)
> fix(member): add warning+confirm when changing primary email

- cron.json
- dont run when `$APP` env is set to `espace-membre-staging*`
- reduce frequency to working days at 18h GMT
> fix(cron): dont run on staging

- src/components/StartupForm/MdEditorCustomHeaderPlugin.tsx
- src/components/StartupForm/StartupForm.tsx
disable les `h1` dans le formulaire d'édition fiche startup
fix #437
> fix(startup-form): disable h1 in product descriptions

- src/app/(private)/(dashboard)/community/create/CommunityCreateMemberPage.tsx
Following @adenoix wording recos when creating a new member
> fix(create-member): adjust email wording

- src/utils/date.ts
La fonction durationBetweenDate affiche "1h" au lieu de "1h30" pour certaines formations. Je pense que c'est dû à une erreur entre minutes et secondes mais : 
- je n'ai pas pu tester en local, la page Formations ne s'affichait pas
- je n'ai pas trouvé de tests unitaires sur ce code
> Fix durationBetweenDate

- __tests__/test-newsletter.ts
- migrations/20241028170333_add_publish_at_column_to_newsletters.ts
- src/@types/db.d.ts
- src/app/(private)/(dashboard)/admin/newsletters/page.tsx
- src/app/(private)/(dashboard)/admin/page.tsx
- src/app/api/newsletters/actions.ts
- src/components/Header.tsx
- src/components/NewsletterForm/NewsletterForm.tsx
- src/components/NewsletterPage/NewsletterPage.tsx
- src/models/actions/newsletter.ts
- src/models/mapper/newsletterMapper.ts
- src/models/newsletter.ts
- src/server/schedulers/newsletterScheduler.ts
- Updated the newsletter logic to use the `publish_at` property as the reference for the publication date and time.
- Ensured that the `publish_at` field is now the primary field to determine when a newsletter will be published.
- This change improves clarity and consistency by explicitly defining the publication schedule using the `publish_at` property.
> feat(newsletter): update to use `publish_at` for scheduling publication

- src/components/NewsletterPage/NewsletterPage.tsx
when a user has Admin access, he can edit the publish_at property of a newsletter. The link to the form to edit this value should appear in the interface.
> chore: add current newsletter edit button if user is admin

- src/components/MemberPage/Email/EmailContainer.tsx
- src/components/MemberPage/MemberContact.tsx
ensure we always show primary email status when incorrect in member card
fix #585
> fix(member): always show primary_email status

- next.config.js
- src/app/api/image/route.ts
- src/app/api/member/[username]/image/route.ts
- src/components/BaseInfoUpdatePage/BaseInfoUpdate.tsx
- src/middleware.ts
- src/models/actions/image.ts
- src/server/config/jwt.config.ts
- add a rewrite rule for backward compatibility to have `/api/public/member/:username/image` as public route (pointing private `/api/member/:username/image`)
- filter out `api/public/` path in middleware
- remove "force-dynamic" from `/api/member/:username/image` and enable build-on-demand with revalidate feature (1h of cache)
- revalidate member only image after upload or delete on S3
> feat: dupe member image as rewrited public route & revalidate

- src/app/api/protected/startup/[startupId]/route.ts
- add `GET:/protected/startup/[startupId]`
- include incubator object in result
> feat(api): add protected get one startup

- .talismanrc
- README.md
- __tests__/users.json
- __tests__/utils.ts
- package-lock.json
- package.json
- src/components/emails/layouts/StandardEmail.tsx
- src/lib/kysely/queries/search.ts
- src/lib/kysely/queries/users.ts
- src/models/actionEvent/actionEvent.ts
- src/server/infra/email/sendInBlue.ts
- src/server/modules/email/email.ts
- src/server/modules/htmlbuilder/htmlbuilder.ts
- src/server/queueing/client.ts
- src/server/queueing/schedule.ts
- src/server/queueing/workers/send-email-to-teams-to-check-on-team-composition.spec.ts
- src/server/queueing/workers/send-email-to-teams-to-check-on-team-composition.ts
- src/server/schedulers/startups/sendEmailToStartupToUpdatePhase.ts
- src/server/scripts/runSendEmail.ts
- src/server/views/templates/emails/teamCompositionEmail/teamCompositionEmail.tsx
- src/server/views/utils/email.ts
- src/utils/gracefulExist.ts
- tsconfig.server.json
- ajoute le script d'envoie d'email tous les 3 mois aux membre des startups
- ~~utilisation de pgboss depuis le bundle next pour gérer ce cron : l'email, les dépendences scss sont géré côté next car le build ttsc ne buildait pas l'utilisation du scss dans l'email.~~
- ~~les taches pgboss sont donc maintenant lancés depuis next (au lieu de cron.ts) grace au run du script start-and-wait-to-init~~
- ~~ajout de storybook : permet la visualisation des emails, et à terme de nos différents composant ui qui commence à être nombreux
(je n'ai pas encore intégré le push sur chromatic à la ci, mais j'ai pour l'instant fait un push manuel)~~
https://67bdd3c4900b1b3e4fce6589-liglwewenr.chromatic.com/?path=/story/emails-templates-teamcompositionemail--complete
- ~~remplacement de ttsc par un build avec …
> feat: send email to startup members with information about members

- .talismanrc
- src/server/views/templates/emails/memberValidationEmail/memberValidationEmail.tsx
Pour avoir la même design que sur les autres emails : 
https://67bdd3c4900b1b3e4fce6589-ossjmiwkla.chromatic.com/?path=/story/emails-templates-membervalidationemail--normal
> ui: wrap memberValidationEmail with standartEmail

- src/app/(private)/(dashboard)/community/[id]/admin-update/page.tsx
Je n'ai pas trouvé de probléme sur l'upload d'image. Par contre il y avait un problème d'affichage de l'image en édition d'un profil via la page admin. L'url du l'avatar n'était pas préfixé par '/api'. Correciton en utilisant getAvatarUrl pour avoir le même comportement partout.
> fix: image path was missing '/api', use getAvatarUrl accross all files

- src/components/IncubatorForm/IncubatorForm.tsx
Le label actuel prête à confusion, on a l'impression qu'il faut mettre tous les produits de l'incubateur. Il s'agit en fait uniquement des produits à mettre en avant sur le site beta.
> chore: changed label for highlighted_startups

- src/components/IncubatorForm/IncubatorForm.tsx
~~ça semble fixé le problème, mais pourtant le default de shape devait devait déjà être "rectangular"~~ Le default de shape dans fichePicture était round, donc c'était bien cassé. La preview de l'image reste cependant différente de comment elle apparaitra sur le site, on peut sans doute travailler la-dessus dans un autre PR => j'ouvre une issue
> chore: incubator logo should be rectangle

- next.config.js
- sentry.client.config.ts
Les changements minimum pour améliorer les choses après avoir tester plein de config.
Les release sont bien envoyé et les source maps uploadés. 
Il y a des mismatchs de source map quand l'erreur vient des chunks next, l'ajout de widenClientFileUpload permet de les avoirs dans les sourcemaps. Ce sont des fichiers minifiés donc c'est pas extrémement lisible. 
A voir si ça nous sert, j'ai pas l'impression que le build soit beaucoup plus long.
J'ai mis les erreurs de minifications/hydration à ignorer. Normalement la config côté sentry.incubateur.net est sensé le faire mais ça ne semble pas s'appliquer.
Ces erreurs floodent trop les alertes à mon avis.
> feat: upload all source maps and ignore minified errors

- __tests__/test-create-member-validation.ts
- src/app/api/member/actions/validateNewMember.ts
- src/models/actionEvent/actionEvent.ts
This prevent an exception when the original event metadata has no incubator set.
> fix(validation): allow null incubator

- src/app/(private)/(dashboard)/startups/[id]/page.tsx
L'accès à la page startup via le github id : `startups/zero-logement-vacant` est cassé. 
On utilise le params.id pour récupérer les comptes matomo et sentry lié au produit, mais params.id est le ghid et non le uuid de la startup : invalid input syntax for type uuid: "zero-logement-vacant"
> fix(startup-page): pass se.uuid instead of ghid

- .talismanrc
- src/components/MemberPage/Email/EmailContainer.tsx
Les utilisateurs avec email OPI devrait quand même voir : changement email principal, changement email secondaire, changement communitcation email.
> chore: allow opi user to changed primary email

- src/components/emails/layouts/StandardEmail.tsx
Les emails ne s'affichent pas dans Infomaniak. Sur infomaniak spécifiquement le css de l'email est mal interprété.
font-family='"Marianne", arial, sans-serif' les quotes dans les quotes cassent le css chez eux et donne pour résultat :
` font-family: "font-size:20px;font-weight:700;line-height:24px;text-align:left;color:#3a3a3a;`, et c'est donc la règle font-size: 0px utilisé par Mjml pour le système de colonne dans les emails qui est appliquée. Le texte ne s'affiche donc pas.
> chore(email): quote within quote break infomaniak reading css style

- __tests__/test-create-member.ts
- src/models/actions/member.ts
On peut inviter un membre en mettant une date dans le futur à plus de 6 mois -> au moment de la changer ses infos il devra forcément changer.
Le membre peut mettre plus de 6 mois au moment de la validation des infos.
> feat: check missions dates on every schema including missions

- src/components/MemberPage/MemberWaitingEmailValidationNotice.tsx
Remplace le titre du message :
`Email en attente de validation` par
`John Tartenpion n'a pas activé sa fiche.`
message actuel:
> chore: make verification waiting message clearer

- src/server/queueing/workers/send-email-to-team-when-new-member.ts
- src/server/queueing/workers/send-validation-email.ts
- src/server/schedulers/emailScheduler.ts
Fait :
- Envoye l'e-mail de validation à l'équipe même si la mission commence dans le futur
- Attend que la mission soit active pour envoyer l'e-mail de vérification au nouveau membre
- Envoye l'e-mail  "un nouveau membre dans votre équipe" à l'équipe même si la mission commence dans le futur
Pour plus tard éventuellement :
Une solution sympa mais qui demanderait un peu plus de changement serait d'utiliser la fonction schedule de pgboss. On pourrait ainsi envoyer l'email à l'équipe uniquement le jour de l'arrivée du/de la membre.
> feat: handle user with mission starting in the futur

- .github/workflows/codeql-analysis.yml
@revolunet je ne suis pas sur de l'intérêt d'avoir codeQL et Sonar en même temps. Ils semblent se récouper sur quelques trucs. Je pense qu'on peut teste.
> ci: codeql what setup on legacy master branch

- src/server/config/index.ts
- src/utils/onboarding/shouldShowOnboardingPanel.ts
Vue avec l'équipe mardi, finalement pas besoin de scoper l'affichage à des incubateurs précis.
> feat: display onboarding to every new user

- .github/workflows/onboarding-checklist-validation.yml
Retire le script qui listent les fichiers :
- le script précédent fait déjà la meme chose
- casse quand les fichiers utilisent des parenthèses
> fix: remove list file that break when special caracter in filename

- src/server/queueing/schedule.ts
Dans Vixie cron (utilisé sur Linux, crontab classique), si à la fois jour_du_mois ET jour_de_la_semaine sont définis, le cron s’exécute si l’un OU l’autre correspond.
Dans 0 8 1,2,3,4,5,6,7 */3 1, le cron au lieu de s'éxécuter le lundi et si le jour 1,2,3,4,5,6,ou 7 du mois, le cron s'éxécute le lundi ou le 1,2,3,4,5,6 ou 7 du mois.
Quick fix : on envoie que le le 1er du mois.
> fix(schedule.ts): cron should not execute every monday every 3 months

- src/app/(private)/(dashboard)/events/page.tsx
- src/components/EventsList.tsx
- src/components/EventsList/EventsList.css
- src/components/EventsList/EventsList.tsx
sur staging il reste un "<a href" qui apparait comme du texte peut être qu'on pourra faire un replace(" ","") pour ce cas precis, j'ai pas réussi à trouver quelques chose qui corriger de façon générique.
> fix(a11y): fix broken links when parsing events content

- src/utils/authoptions.ts
This allows users to login even when their email is not the same case in espace-membre and ProConnect
> fix(ProConnect): allow differents cases in email login
